swagger: "2.0"

info:
  version: 1.0.0
  title: backend
  description: hiec APIs

basePath: /api

tag: 
- name: "auth"
  description: "Permission to send request to API"

consumes:
  - application/json
produces:
  - application/json


paths:
  /auth/sign-out:
    get:
      tags:
        - auth
      description: logout
      paramenters:
        - name: token
          in: query
          description: token to be disabled
          schema:
            type: string
  /auth/sign-in:
    post:
      tags:
        - auth
      description: log in
      paramenters:
        - name: email
          in: body
          description: user email
          type: string
        - name: password
          in: body
          description: user password
          type: string
  